## encoding = utf-8

#namespace :db do
#  namespace :seed do
#    desc "Add new example's data to database"
#    task :add_items => :environment do
#      items = [
#        { :id => 6, :user_id => 1 },
#        { :id => 7, :user_id => 1 },
#        { :id => 8, :user_id => 1 },
#        { :id => 9, :user_id => 1 },
#        { :id => 10, :user_id => 1 },
#        { :id => 11, :user_id => 1 }
#      ]

#      items.each do |item|
#        i = Item.new(item)
#        i.id = item[:id]
#        i.save
#      end

#      bis = [
#      {
#        :id => 6,
#        :gtin => '4607085473498',
#        :item_description	=> 'Вода минеральная негазированная Aqua Minerale',
#        :status => 'published',
#        :user_id => '1',
#        :internal_item_id => '6',
#        :despatch_unit    => 1,
#        :invoice_unit	  => 0,
#        :order_unit => 0,
#        :consumer_unit => 0,
#        :manufacturer_name => 'Pepsico',
#        :manufacturer_gln => '1000000000010',
#        :content_uom => 'LTR',
#        :gross_weight => '700',
#        :vat => '57',
#        :gpc_code => '10000232',
#        :country_of_origin_code => 'RU',
#        :minimum_durability_from_arrival => '10',
#        :packaging_type => 'KF',
#        :height => '1',
#        :depth => '1',
#        :width => '1',
#        :content => '0.600',
#        :brand  => 'Aqua Minerale',
#        :subbrand => '',
#        :functional => 'Drink water',
#        :item_id => 6,
#        :net_weight => 650
#      },
#      {
#        :id => 7,
#        :gtin => '4607085451665',
#        :item_description	=> 'Вода минеральная газированная Perrier',
#        :status => 'published',
#        :user_id => '1',
#        :internal_item_id => '7',
#        :despatch_unit    => 1,
#        :invoice_unit	  => 0,
#        :order_unit => 0,
#        :consumer_unit => 0,
#        :manufacturer_name => 'Perrier',
#        :manufacturer_gln => '1000000000012',
#        :content_uom => 'LTR',
#        :gross_weight => '400',
#        :vat => '57',
#        :gpc_code => '10000232',
#        :country_of_origin_code => 'RU',
#        :minimum_durability_from_arrival => '10',
#        :packaging_type => 'BO',
#        :height => '1',
#        :depth => '1',
#        :width => '1',
#        :content => '0.330',
#        :brand  => 'Perrier',
#        :subbrand => '',
#        :functional => 'Drink water',
#        :item_id => 7,
#        :net_weight => 350
#      },
#      {
#        :id => 8,
#        :gtin => '4607085133579',
#        :item_description	=> 'Вода минеральная негазированная Vittel',
#        :status => 'published',
#        :user_id => '1',
#        :internal_item_id => '8',
#        :despatch_unit    => 1,
#        :invoice_unit	  => 0,
#        :order_unit => 0,
#        :consumer_unit => 0,
#        :manufacturer_name => 'Vittel',
#        :manufacturer_gln => '1000000000013',
#        :content_uom => 'LTR',
#        :gross_weight => '400',
#        :vat => '57',
#        :gpc_code => '10000232',
#        :country_of_origin_code => 'RU',
#        :minimum_durability_from_arrival => '10',
#        :packaging_type => 'KF',
#        :height => '1',
#        :depth => '1',
#        :width => '1',
#        :content => '0.330',
#        :brand  => 'Vittel',
#        :subbrand => '',
#        :functional => 'Drink water',
#        :item_id => 8,
#        :net_weight => 350
#      },
#      {
#        :id => 9,
#        :gtin => '4607085187555',
#        :item_description	=> 'Вода минеральная негазированная Evian',
#        :status => 'published',
#        :user_id => '1',
#        :internal_item_id => '9',
#        :despatch_unit    => 1,
#        :invoice_unit	  => 0,
#        :order_unit => 0,
#        :consumer_unit => 0,
#        :manufacturer_name => 'Vittel',
#        :manufacturer_gln => '1000000000013',
#        :content_uom => 'LTR',
#        :gross_weight => '600',
#        :vat => '57',
#        :gpc_code => '10000232',
#        :country_of_origin_code => 'RU',
#        :minimum_durability_from_arrival => '10',
#        :packaging_type => 'KF',
#        :height => '1',
#        :depth => '1',
#        :width => '1',
#        :content => '0.500',
#        :brand  => 'Vittel',
#        :subbrand => '',
#        :functional => 'Drink water',
#        :item_id => 9,
#        :net_weight => 530
#      },
#      {
#        :id => 10,
#        :gtin => '46070851172931',
#        :item_description	=> 'Мыло хозяйственное Duru',
#        :status => 'published',
#        :user_id => '1',
#        :internal_item_id => '10',
#        :despatch_unit    => 1,
#        :invoice_unit	  => 0,
#        :order_unit => 0,
#        :consumer_unit => 0,
#        :manufacturer_name => 'Evyap',
#        :manufacturer_gln => '1000000000099',
#        :content_uom => 'GRM',
#        :gross_weight => '150',
#        :vat => '57',
#        :gpc_code => '10000813',
#        :country_of_origin_code => 'RU',
#        :minimum_durability_from_arrival => '10',
#        :packaging_type => 'KF',
#        :height => '1',
#        :depth => '1',
#        :width => '1',
#        :content => '0.140',
#        :brand  => 'Duru',
#        :subbrand => '',
#        :functional => 'Soap',
#        :item_id => 10,
#        :net_weight => 140
#      },
#      {
#        :id => 11,
#        :gtin => '46070851172932',
#        :item_description	=> 'Мыло туалетное DURU Морские Минералы+Крем',
#        :status => 'published',
#        :user_id => '1',
#        :internal_item_id => '11',
#        :despatch_unit    => 1,
#        :invoice_unit	  => 0,
#        :order_unit => 0,
#        :consumer_unit => 0,
#        :manufacturer_name => 'Evyap',
#        :manufacturer_gln => '1000000000099',
#        :content_uom => 'GRM',
#        :gross_weight => '100',
#        :vat => '57',
#        :gpc_code => '10000813',
#        :country_of_origin_code => 'RU',
#        :minimum_durability_from_arrival => '10',
#        :packaging_type => 'PK',
#        :height => '1',
#        :depth => '1',
#        :width => '1',
#        :content => '0.100',
#        :brand  => 'Duru',
#        :subbrand => '',
#        :functional => 'Soap',
#        :item_id => 11,
#        :net_weight => 105
#      }]

#      bis.each do |base_item|
#        bi = BaseItem.new(base_item)
#        bi.id = base_item[:id]
#        bi.save
#        puts bi.errors.full_messages
#      end
#    end
#  end
#end

