source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '3.0.7'
gem 'authlogic', '3.0.3'
gem 'aasm', :require => 'aasm'
gem 'responds_to_parent',:git => 'https://github.com/kennon/responds_to_parent.git'
gem 'will_paginate', '~> 3.0.beta'
gem 'dynamic_form'
gem 'jrails'
gem 'jquery-rails'
gem 'rmagick', :require => 'RMagick'
gem 'pg', :require => 'pg'
gem 'nested_set'
gem 'jrails'
gem 'jquery-rails'
gem 'rails3-jquery-autocomplete', :git => 'https://github.com/pavel-so/rails3-jquery-autocomplete.git'
gem 'xml2xls',:path => 'vendor/gems/xml2xls-0.2.2'
#gem 'spreadsheet'
gem 'rubyzip'
gem 'ruby-xslt'
gem 'exception_notification', :git => 'https://github.com/rails/exception_notification.git', :require => 'exception_notifier'
group :development, :test do
  gem 'ZenTest'
  gem 'annotate'
  gem 'capybara', '0.4.1.2'
  gem 'cucumber'
  gem 'cucumber-rails', '0.3.2', :require => false
  gem 'database_cleaner'
  gem 'headless'
  gem 'parseexcel'
  gem 'pickle'
  gem 'rails-erd'
  gem 'rspec', '1.3.2', :require => 'spec'
  gem 'rspec-rails', '1.3.4', :require => false
  gem 'selenium-webdriver', '0.2.2'
  gem 'spork'
  gem 'test-unit'
  gem 'thoughtbot-factory_girl', :require => false
end
