defaults: &defaults
  host: localhost
  # Disable dynamic fields
  allow_dynamic_fields: false
  autocreate_indexes: false
  # Enable identity maps
  identity_map_enabled: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  skip_version_check: true

development:
  <<: *defaults
  database: gm_dev

test:
  <<: *defaults
  database: gm_test

cucumber:
  <<: *defaults
  database: gm_cucumber

demo:
  <<: *defaults
  database: gm_qa

qa:
  <<: *defaults
  database: gm_qa

staging:
  <<: *defaults
  host: 184.106.209.38
  port: 38017
  username: gmadmin
  password: pRhQ19Xj
  database: gm_staging

# set these environment variables on your prod server
production:
  <<: *defaults
  database: gm_production
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
#  # Enable identity maps
#  identity_map_enabled: true
#  # Disable dynamic fields
#  allow_dynamic_fields: false
#  skip_version_check: true
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
