defaults: &defaults
  host: localhost
  # Enable identity maps
  identity_map_enabled: true
  # Disable dynamic fields
  allow_dynamic_fields: false
  skip_version_check: true

development:
  <<: *defaults
  database: gm_dev

test:
  <<: *defaults
  database: gm_test

cucumber:
  <<: *defaults
  database: gm_cucumber

qa:
  <<: *defaults
  database: gm_qa

staging:
  <<: *defaults
  database: gm_staging

# set these environment variables on your prod server
production:
  <<: *defaults
  database: gm_production
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
#  # Enable identity maps
#  identity_map_enabled: true
#  # Disable dynamic fields
#  allow_dynamic_fields: false
#  skip_version_check: true
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
