development:
  host: localhost
  database: gm_dev
  # Enable identity maps
  identity_map_enabled: true
  # Disable dynamic fields
  allow_dynamic_fields: false
  skip_version_check: true

test:
  host: localhost
  database: gm_test
  # Enable identity maps
  identity_map_enabled: true
  # Disable dynamic fields
  allow_dynamic_fields: false
  skip_version_check: true

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # Enable identity maps
  identity_map_enabled: true
  # Disable dynamic fields
  allow_dynamic_fields: false
  skip_version_check: true
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
