defaults: &defaults
  airbrake:
    api_key: 'abcdf4a014f0a68351c0c38a81f95a06'

  rackspace:
    api_key: '84c16f1d53a901aab8c91bc49a9ba491'
    fog_host: "http://c285322.r22.cf1.rackcdn.com"
    username: 'mrost'

  uservoice:
    api_key: 'b5c617c4a074cd3c3e016c13650f0099'


development:
  <<: *defaults

test:
  <<: *defaults

cucumber:
  <<: *defaults

qa:
  <<: *defaults

  rackspace:
    api_key: '84c16f1d53a901aab8c91bc49a9ba491'
    fog_host: "http://c285315.r15.cf1.rackcdn.com"
    username: 'mrost'

staging:
  <<: *defaults

  rackspace:
    api_key: '84c16f1d53a901aab8c91bc49a9ba491'
    fog_host: "http://c285316.r16.cf1.rackcdn.com"
    username: 'mrost'

production:
  <<: *defaults

  rackspace:
    api_key: '84c16f1d53a901aab8c91bc49a9ba491'
    fog_host: "http://c285317.r17.cf1.rackcdn.com"
    username: 'mrost'
