defaults: &defaults
  project_name: "GoodsMaster"
  app_subdomain: "app"

  page_title_header: "h1"

development:
  <<: *defaults

test:
  <<: *defaults

cucumber:
  <<: *defaults

testing:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults