defaults: &defaults
  project_name: "GoodsMaster"
  app_subdomain: "app"
  send_mail_from: "system@GoodsMasterHQ.com"

  page_title_header: "h1"

development:
  <<: *defaults

test:
  <<: *defaults

cucumber:
  <<: *defaults

qa:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults