defaults: &defaults
  project_name: "GoodsMaster"
  app_subdomain: "app"

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

cucumber:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults