defaults: &defaults
  project_name: "GoodsMaster"
  copyright: "Goods Master Inc."
  app_subdomain: "app"
  send_mail_from: "system@GoodsMasterHQ.com"

  auto_complete:
    limit: 10

  links:
    project_home: "http://GoodsMasterHQ.com"
    feedback: "http://feedback.goodsmasterhq.com"
    terms: "http://goodsmasterhq.com/terms"
    privacy: "http://goodsmasterhq.com/privacy"
  events:
    recent_max_count: 50
    recent_max_count_for_admin: 50
    collapse_timeframe: 60

  tags:
    maximum_length: 20
    separator: ","


  # Those settings are from secured_settings.yml
  # They are here to allow precompile assets before secured_settings.yml is copied.
  airbrake:
    api_key: 'abc'
  rackspace:
    api_key: 'abc'
    fog_host: "http://c285322.r22.cf1.rackcdn.com"
    username: 'abc'
  uservoice:
    api_key: 'abc'

development:
  <<: *defaults

test:
  <<: *defaults

cucumber:
  <<: *defaults

qa:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults