defaults: &defaults
  project_name: "GoodsMaster"
  copyright: "GoodsMaster Inc."
  app_subdomain: "app"
  send_mail_from: "system@GoodsMasterHQ.com"

  auto_complete:
    limit: 10

  events:
    recent_max_count: 50
    recent_max_count_for_admin: 50
    collapse_timeframe: 60

  links:
    project_home: "http://GoodsMasterHQ.com"
    feedback: "http://feedback.goodsmasterhq.com"
    terms: "http://goodsmasterhq.com/terms"
    privacy: "http://goodsmasterhq.com/privacy"

  products:
    limit: 50
    group_options: "functional_name manufacturer brand"
    default_group: "functional_name"

  tags:
    maximum_length: 20
    separator: ","

development:
  <<: *defaults

  products:
    limit: 10
    group_options: "functional_name manufacturer brand"
    default_group: "functional_name"

test:
  <<: *defaults
  products:
    limit: 10
    group_options: "functional_name manufacturer brand"
    default_group: "functional_name"

cucumber:
  <<: *defaults

  products:
    limit: 6
    group_options: "functional_name manufacturer brand"
    default_group: "functional_name"

qa:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults