uservoice_options:
  key: goodsmaster
  host: goodsmaster.uservoice.com
  forum: 143701
uservoice_api:
  api_key: <%= Settings.uservoice.api_key %>
widget:
  path: widget.uservoice.com/g7Tv9aEYEg68khcRp9SzwA.js
