uservoice_options:
  # required
  key: getmasterdata
  host: getmasterdata.uservoice.com
  forum: 128773

uservoice_api:
  api_key: 92205a47af50540dbd25f2fd8ff8c65f
widget:
  path: widget.uservoice.com/wKfR7pDTG1JzedMmJMU7w.js

