:en:
- - квадратный метр
  - MTK
- - кг #килограм
  - KGM
- - комплект
  - SET
- - кубометр
  - MTQ
- - лист
  - ST
- - л #литр
  - LTR
- - пара
  - PR
- - м #метр
  - MTR
- - штука
  - PCE
- - см #
  - CMT
- - г #
  - GRM
- - мл #
  - MLT
- - мм #
  - MMT

:ru:
- - квадратный метр
  - MTK
- - кг #килограм
  - KGM
- - комплект
  - SET
- - кубометр
  - MTQ
- - лист
  - ST
- - л #литр
  - LTR
- - пара
  - PR
- - м #метр
  - MTR
- - штука
  - PCE
- - см #сантиметр
  - CMT
- - г #грамм
  - GRM
- - мл #миллилитр
  - MLT
- - мм #миллиметр
  - MMT

