:en:
- - square meter
  - MTK
- - kilogram #килограм
  - KGM
- - set
  - SET
- - cubic meter
  - MTQ
- - sheet
  - ST
- - liter #литр
  - LTR
- - pair
  - PR
- - meter #метр
  - MTR
- - piece
  - PCE
- - centimeter #
  - CMT
- - gramme #
  - GRM
- - milliliter #
  - MLT
- - millimeter #
  - MMT

:ru:
- - квадратный метр
  - MTK
- - кг #килограм
  - KGM
- - комплект
  - SET
- - кубометр
  - MTQ
- - лист
  - ST
- - л #литр
  - LTR
- - пара
  - PR
- - м #метр
  - MTR
- - штука
  - PCE
- - см #сантиметр
  - CMT
- - г #грамм
  - GRM
- - мл #миллилитр
  - MLT
- - мм #миллиметр
  - MMT

