:en:
  PUE: PU #Tray packed in plastic
  BX: BX
  NE: NE #Unpacked
  TU: TU
  BO: BO
  TB: TB
  IC: BPK #Package, display, plastic
  AE: AE
  SW: SW
  DS: PU #NEW #Tray, one layer no cover, plastic
  PU: PU
  PK: PK #Package
  CS: CS
  BG: BG
  CT: CT
  CU: CU
  BJ: BJ
  JR: JR
  PLP: PLP #Peel pack
  CX: CN #Can, cylindrical
  CA: CN #Can, rectangular
  EN: EN #Envelope
  UVQ: STW #Wrapped in plastic sheet
  PA: WP #Packet
  NU: NT #Net, tube, plastic
  DV: PU #Tray, two layers no cover, plastic tray
  DA: CR #Crate, multiple layer, plastic
  EC: BG #Bag, plastic
  BME: BLP #Blister pack
  CBL: BO #Container bottle like
  WRP: WRP #Wrapper
  BE: MTP #Bundle
  SH: PK #Sachet
  FP: PK #Filmpack
  DR: PK #Drum
  FPE: PK #Foil packed
  APE: PK #Aluminium packed
  IB: BX #Package, display, cardboard
  DPE: BX #Display package


  
