:en:
- :code: AE
  :name: Aerosol
  :id: 1
- :code: AM
  :name: Ampoule
  :id: 2
- :code: AT
  :name: Atomizer
  :id: 3
- :code: BG
  :name: Bag
  :id: 4
- :code: NEW
  :name: Bag in Box
  :id: 5
- :code: NEW
  :name: Banded package
  :id: 6
- :code: BA
  :name: Barrel
  :id: 7
- :code: BK
  :name: Basket
  :id: 8
- :code: NEW
  :name: Blister pack
  :id: 9
- :code: BO
  :name: Bottle
  :id: 10
- :code: BX
  :name: Box
  :id: 11
- :code: NEW
  :name: Brick
  :id: 12
- :code: BJ
  :name: Bucket
  :id: 13
- :code: CG
  :name: Cage
  :id: 14
- :code: NEW
  :name: Can
  :id: 15
- :code: NEW
  :name: Card
  :id: 16
- :code: CT
  :name: Carton
  :id: 17
- :code: CS
  :name: Case
  :id: 18
- :code: CR
  :name: Crate
  :id: 19
- :code: CU
  :name: Cup
  :id: 20
- :code: CY
  :name: Cylinder
  :id: 21
- :code: DN
  :name: Dispenser
  :id: 22
- :code: EN
  :name: Envelope
  :id: 23
- :code: NEW
  :name: Flexible Intermediate Bulk Container
  :id: 24
- :code: NEW
  :name: Gable top
  :id: 25
- :code: JR
  :name: Jar
  :id: 26
- :code: JG
  :name: Jug
  :id: 27
- :code: NEW
  :name: Multipack
  :id: 28
- :code: NT
  :name: Net
  :id: 29
- :code: NEW
  :name: Not packed
  :id: 30
- :code: NEW
  :name: Packed, unspecified
  :id: 31
- :code: PX
  :name: Pallet
  :id: 32
- :code: PB
  :name: Pallet Box
  :id: 33
- :code: NEW
  :name: Peel pack
  :id: 34
- :code: PO
  :name: Pouch
  :id: 35
- :code: RK
  :name: Rack
  :id: 36
- :code: RL
  :name: Reel
  :id: 37
- :code: SW
  :name: Shrinkwrapped
  :id: 38
- :code: NEW
  :name: Sleeve
  :id: 39
- :code: NEW
  :name: Stretchwrapped
  :id: 40
- :code: PU
  :name: Tray
  :id: 41
- :code: TB
  :name: Tub
  :id: 42
- :code: TU
  :name: Tube
  :id: 43
- :code: VP
  :name: Vacuum-packed
  :id: 44
- :code: NEW
  :name: Wrapper
  :id: 45

:ru:
- :code: AE
  :name: Aerosol
  :id: 1
- :code: AM
  :name: Ampoule
  :id: 2
- :code: AT
  :name: Atomizer
  :id: 3
- :code: BG
  :name: Bag
  :id: 4
- :code: NEW
  :name: Bag in Box
  :id: 5
- :code: NEW
  :name: Banded package
  :id: 6
- :code: BA
  :name: Barrel
  :id: 7
- :code: BK
  :name: Basket
  :id: 8
- :code: NEW
  :name: Blister pack
  :id: 9
- :code: BO
  :name: Bottle
  :id: 10
- :code: BX
  :name: Box
  :id: 11
- :code: NEW
  :name: Brick
  :id: 12
- :code: BJ
  :name: Bucket
  :id: 13
- :code: CG
  :name: Cage
  :id: 14
- :code: NEW
  :name: Can
  :id: 15
- :code: NEW
  :name: Card
  :id: 16
- :code: CT
  :name: Carton
  :id: 17
- :code: CS
  :name: Case
  :id: 18
- :code: CR
  :name: Crate
  :id: 19
- :code: CU
  :name: Cup
  :id: 20
- :code: CY
  :name: Cylinder
  :id: 21
- :code: DN
  :name: Dispenser
  :id: 22
- :code: EN
  :name: Envelope
  :id: 23
- :code: NEW
  :name: Flexible Intermediate Bulk Container
  :id: 24
- :code: NEW
  :name: Gable top
  :id: 25
- :code: JR
  :name: Jar
  :id: 26
- :code: JG
  :name: Jug
  :id: 27
- :code: NEW
  :name: Multipack
  :id: 28
- :code: NT
  :name: Net
  :id: 29
- :code: NEW
  :name: Not packed
  :id: 30
- :code: NEW
  :name: Packed, unspecified
  :id: 31
- :code: PX
  :name: Pallet
  :id: 32
- :code: PB
  :name: Pallet Box
  :id: 33
- :code: NEW
  :name: Peel pack
  :id: 34
- :code: PO
  :name: Pouch
  :id: 35
- :code: RK
  :name: Rack
  :id: 36
- :code: RL
  :name: Reel
  :id: 37
- :code: SW
  :name: Shrinkwrapped
  :id: 38
- :code: NEW
  :name: Sleeve
  :id: 39
- :code: NEW
  :name: Stretchwrapped
  :id: 40
- :code: PU
  :name: Tray
  :id: 41
- :code: TB
  :name: Tub
  :id: 42
- :code: TU
  :name: Tube
  :id: 43
- :code: VP
  :name: Vacuum-packed
  :id: 44
- :code: NEW
  :name: Wrapper
  :id: 45

