:en:
- :name: PUE
  :code: PUE
  :id: 1
- :name: ""
  :code: ""
  :id: 2
- :name: BX
  :code: BX
  :id: 3
- :name: APE
  :code: APE
  :id: 4
- :name: NE
  :code: NE
  :id: 5
- :name: TU
  :code: TU
  :id: 6
- :name: CBL
  :code: CBL
  :id: 7
- :name: BO
  :code: BO
  :id: 8
- :name: IB
  :code: IB
  :id: 9
- :name: TB
  :code: TB
  :id: 10
- :name: DPE
  :code: DPE
  :id: 11
- :name: BE
  :code: BE
  :id: 12
- :name: DR
  :code: DR
  :id: 13
- :name: IC
  :code: IC
  :id: 14
- :name: AE
  :code: AE
  :id: 15
- :name: SW
  :code: SW
  :id: 16
- :name: BME
  :code: BME
  :id: 17
- :name: DS
  :code: DS
  :id: 18
- :name: PU
  :code: PU
  :id: 19
- :name: PK
  :code: PK
  :id: 20
- :name: CS
  :code: CS
  :id: 21
- :name: FPE
  :code: FPE
  :id: 22
- :name: BG
  :code: BG
  :id: 23
- :name: UVQ
  :code: UVQ
  :id: 24
- :name: PA
  :code: PA
  :id: 25
- :name: CT
  :code: CT
  :id: 26
- :name: CU
  :code: CU
  :id: 27
- :name: NU
  :code: NU
  :id: 28
- :name: DV
  :code: DV
  :id: 29
- :name: DA
  :code: DA
  :id: 30
- :name: BJ
  :code: BJ
  :id: 31
- :name: JR
  :code: JR
  :id: 32
- :name: EC
  :code: EC
  :id: 33
- :name: CA
  :code: CA
  :id: 34
- :name: EN
  :code: EN
  :id: 35
- :name: PLP
  :code: PLP
  :id: 36
- :name: FP
  :code: FP
  :id: 37
- :name: SH
  :code: SH
  :id: 38
- :name: WRP
  :code: WRP
  :id: 39
- :name: CX
  :code: CX
  :id: 40
:ru:
- :name: PUE
  :code: PUE
  :id: 1
- :name: ""
  :code: ""
  :id: 2
- :name: BX
  :code: BX
  :id: 3
- :name: APE
  :code: APE
  :id: 4
- :name: NE
  :code: NE
  :id: 5
- :name: TU
  :code: TU
  :id: 6
- :name: CBL
  :code: CBL
  :id: 7
- :name: BO
  :code: BO
  :id: 8
- :name: IB
  :code: IB
  :id: 9
- :name: TB
  :code: TB
  :id: 10
- :name: DPE
  :code: DPE
  :id: 11
- :name: BE
  :code: BE
  :id: 12
- :name: DR
  :code: DR
  :id: 13
- :name: IC
  :code: IC
  :id: 14
- :name: AE
  :code: AE
  :id: 15
- :name: SW
  :code: SW
  :id: 16
- :name: BME
  :code: BME
  :id: 17
- :name: DS
  :code: DS
  :id: 18
- :name: PU
  :code: PU
  :id: 19
- :name: PK
  :code: PK
  :id: 20
- :name: CS
  :code: CS
  :id: 21
- :name: FPE
  :code: FPE
  :id: 22
- :name: BG
  :code: BG
  :id: 23
- :name: UVQ
  :code: UVQ
  :id: 24
- :name: PA
  :code: PA
  :id: 25
- :name: CT
  :code: CT
  :id: 26
- :name: CU
  :code: CU
  :id: 27
- :name: NU
  :code: NU
  :id: 28
- :name: DV
  :code: DV
  :id: 29
- :name: DA
  :code: DA
  :id: 30
- :name: BJ
  :code: BJ
  :id: 31
- :name: JR
  :code: JR
  :id: 32
- :name: EC
  :code: EC
  :id: 33
- :name: CA
  :code: CA
  :id: 34
- :name: EN
  :code: EN
  :id: 35
- :name: PLP
  :code: PLP
  :id: 36
- :name: FP
  :code: FP
  :id: 37
- :name: SH
  :code: SH
  :id: 38
- :name: WRP
  :code: WRP
  :id: 39
- :name: CX
  :code: CX
  :id: 40

#:en:
#- :code: AE
#  :name: Aerosol
#  :id: 1
#- :code: AM
#  :name: Ampoule
#  :id: 2
#- :code: AT
#  :name: Atomizer
#  :id: 3
#- :code: BG
#  :name: Bag
#  :id: 4
#- :code: NEW
#  :name: Bag in Box
#  :id: 5
#- :code: NEW
#  :name: :Banded package
#  :id: 6
#- :code: BA
#  :name: Barrel
#  :id: 7
#- :code: BK
#  :name: Basket
#  :id: 8
#- :code: NEW
#  :name: Blister pack
#  :id: 9
#- :code: BO
#  :name: Bottle
#  :id: 10
#- :code: BX
#  :name: Box
#  :id: 11
#- :code: NEW
#  :name: Brick
#  :id: 12
#- :code: BJ
#  :name: Bucket
#  :id: 13
#- :code: CG
#  :name: Cage
#  :id: 14
#- :code: NEW
#  :name: Can
#  :id: 15
#- :code: NEW
#  :name: Card
#  :id: 16
#- :code: CT
#  :name: Carton
#  :id: 17
#- :code: CS
#  :name: Case
#  :id: 18
#- :code: CR
#  :name: Crate
#  :id: 19
#- :code: CU
#  :name: Cup
#  :id: 20
#- :code: CY
#  :name: Cylinder
#  :id: 21
#- :code: DN
#  :name: Dispenser
#  :id: 22
#- :code: EShrinkwrappedN
#  :name: Envelope
#  :id: 23
#- :code: NEW
#  :name: Flexible Intermediate Bulk Container
#  :id: 24
#- :code: NEW
#  :name: Gable top
#  :id: 25
#- :code: JR
#  :name: Jar
#  :id: 26
#- :code: JG
#  :name: Jug
#  :id: 27
#- :code: NEW
#  :name: Multipack
#  :id: 28
#- :code: NT
#  :name: Net
#  :id: 29
#- :code: NEW
#  :name: Not packed
#  :id: 30
#- :code: NEW
#  :name: Packed, unspecified
#  :id: 31
#- :code: PX
#  :name: Pallet
#  :id: 32
#- :code: PB
#  :name: Pallet Box
#  :id: 33
#- :code: NEW
#  :name: Peel pack
#  :id: 34
#- :code: PO
#  :name: Pouch
#  :id: 35
#- :code: RK
#  :name: Rack
#  :id: 36
#- :code: RL
#  :name: Reel
#  :id: 37
#- :code: SW
#  :name: Shrinkwrapped
#  :id: 38
#- :code: NEW
#  :name: Sleeve
#  :id: 39
#- :code: NEW
#  :name: Stretchwrapped
#  :id: 40
#- :code: PU
#  :name: Tray
#  :id: 41
#- :code: TB
#  :name: Tub
#  :id: 42
#- :code: TU
#  :name: Tube
#  :id: 43
#- :code: VP
#  :name: Vacuum-packed
#  :id: 44
#- :code: NEW
#  :name: Wrapper
#  :id: 45

#:ru:
#- :code: AE
#  :name: Aerosol
#  :id: 1
#- :code: AM
#  :name: Ampoule
#  :id: 2
#- :code: AT
#  :name: Atomizer
#  :id: 3
#- :code: BG
#  :name: Bag
#  :id: 4
#- :code: NEW
#  :name: Bag in Box
#  :id: 5
#- :code: NEW
#  :name: Banded package
#  :id: 6
#- :code: BA
#  :name: Barrel
#  :id: 7
#- :code: BK
#  :name: Basket
#  :id: 8
#- :code: NEW
#  :name: Blister pack
#  :id: 9
#- :code: BO
#  :name: Bottle
#  :id: 10
#- :code: BX
#  :name: Box
#  :id: 11
#- :code: NEW
#  :name: Brick
#  :id: 12
#- :code: BJ
#  :name: Bucket
#  :id: 13
#- :code: CG
#  :name: Cage
#  :id: 14
#- :code: NEW
#  :name: Can
#  :id: 15
#- :code: NEW
#  :name: Card
#  :id: 16
#- :code: CT
#  :name: Carton
#  :id: 17
#- :code: CS
#  :name: Case
#  :id: 18
#- :code: CR
#  :name: Crate
#  :id: 19
#- :code: CU
#  :name: Cup
#  :id: 20
#- :code: CY
#  :name: Cylinder
#  :id: 21
#- :code: DN
#  :name: Dispenser
#  :id: 22
#- :code: EN
#  :name: Envelope
#  :id: 23
#- :code: NEW
#  :name: Flexible Intermediate Bulk Container
#  :id: 24
#- :code: NEW
#  :name: Gable top
#  :id: 25
#- :code: JR
#  :name: Jar
#  :id: 26
#- :code: JG
#  :name: Jug
#  :id: 27
#- :code: NEW
#  :name: Multipack
#  :id: 28
#- :code: NT
#  :name: Net
#  :id: 29
#- :code: NEW
#  :name: Not packed
#  :id: 30
#- :code: NEW
#  :name: Packed, unspecified
#  :id: 31
#- :code: PX
#  :name: Pallet
#  :id: 32
#- :code: PB
#  :name: Pallet Box
#  :id: 33
#- :code: NEW
#  :name: Peel pack
#  :id: 34
#- :code: PO
#  :name: Pouch
#  :id: 35
#- :code: RK
#  :name: Rack
#  :id: 36
#- :code: RL
#  :name: Reel
#  :id: 37
#- :code: SW
#  :name: Shrinkwrapped
#  :id: 38
#- :code: NEW
#  :name: Sleeve
#  :id: 39
#- :code: NEW
#  :name: Stretchwrapped
#  :id: 40
#- :code: PU
#  :name: Tray
#  :id: 41
#- :code: TB
#  :name: Tub
#  :id: 42
#- :code: TU
#  :name: Tube
#  :id: 43
#- :code: VP
#  :name: Vacuum-packed
#  :id: 44
#- :code: NEW
#  :name: Wrapper
#  :id: 45

